Updated to put the launch as a config map
This makes the yaml for the pod simpler

diff --git a/openfoam-job/templates/openfoam-job.yaml b/openfoam-job/templates/openfoam-job.yaml
--- a/openfoam-job/templates/openfoam-job.yaml
+++ b/openfoam-job/templates/openfoam-job.yaml
@@ -24,79 +24,11 @@ spec:
             mellanox.com/shared_hca_rdma: 1
         command:
         - "bash"
-        - "-c"
+        - "/opt/actions/hpcx-run"
         - |
-          SECONDS=0
-           
-          # Correct permissions for the /scratch filesystem
-          chmod 1777 /tmp
-              
-          printf "[ %6d ] Starting SSH daemon\n" $SECONDS
-          /etc/init.d/ssh start
-          
-          printf "[ %6d ] Creating IP file (/home/jobs/{{ .Release.Name }}/hosts/${POD_IP})\n" $SECONDS
-          mkdir -p /home/jobs/{{ .Release.Name }}/hosts
-          touch /home/jobs/{{ .Release.Name }}/hosts/${POD_IP}
-          
-          if [ "${JOB_COMPLETION_INDEX}" = "0" ]; then
-            printf "[ %6d ] Adding user with homedir ({{ .Values.userName }})\n" $SECONDS
-            addgroup --gid {{ .Values.groupId }} {{ .Values.groupName }}
-            adduser --disabled-password --uid {{ .Values.userId }} --ingroup {{ .Values.groupName }} --home /home/{{ .Values.userName }} --gecos "" {{ .Values.userName }}
-            printf "[ %6d ] User added ($(getent passwd {{ .Values.userName }} > /dev/null))\n" $SECONDS
-            
-            if [[ ! -d /home/{{ .Values.userName }}/.ssh ]]; then
-              printf "[ %6d ] Creating ssh key\n" $SECONDS
-              cat <<EOF | sudo -u {{ .Values.userName }} bash
-          ssh-keygen -q -f /home/{{ .Values.userName }}/.ssh/id_rsa -N ''
-          echo -e "Host *\n\tStrictHostKeyChecking no" >> /home/{{ .Values.userName }}/.ssh/config
-          chmod 600 /home/{{ .Values.userName }}/.ssh/config
-          cp /home/{{ .Values.userName }}/.ssh/id_rsa.pub /home/{{ .Values.userName }}/.ssh/authorized_keys
-          echo -e "\n . /opt/openfoam10/etc/bashrc" >> ~/.bashrc
-          EOF
-            else
-              echo -e "SSH keys already exist"
-            fi
-            
-            printf "[ %6d ] Waiting for hosts\n" $SECONDS
-            while [ "$(ls /home/jobs/{{ .Release.Name }}/hosts | wc -l)" != "{{ .Values.numberOfNodes }}" ]; do
-              printf "[ %6d ] - hosts available: $(ls /home/jobs/{{ .Release.Name }}/hosts | wc -l) out of {{ .Values.numberOfNodes }}\n" $SECONDS
-              sleep 10
-            done
-            
-            printf "[ %6d ] Creating hostfile\n" $SECONDS
-            ls /home/jobs/{{ .Release.Name }}/hosts > /home/{{ .Values.userName }}/hostfile
-            printf "[ %6d ] Hostfile contents:\n" $SECONDS
-            cat /home/{{ .Values.userName }}/hostfile
-            chown {{ .Values.userName }}:{{ .Values.groupName }} /home/{{ .Values.userName }}/hostfile
-            chmod +r /home/{{ .Values.userName }}/hostfile
-            
-            printf "[ %6d ] Launching MPI\n" $SECONDS
-            cat <<EOF | su - {{ .Values.userName }}
-          module load mpi/hpcx
           cp /opt/actions/openfoam-demo-action ./openfoam_demo.sh
           chmod u+x ./openfoam_demo.sh 
           ./openfoam_demo.sh
-          EOF
-            RESULT=$?
-            
-            printf "[ %6d ] Writing completion file (/home/jobs/{{ .Release.Name }}/complete)\n" $SECONDS
-            if [ "$RESULT" = "0" ]; then
-              echo "success" > /home/jobs/{{ .Release.Name }}/complete
-            else
-              echo "failure ($RESULT)" > /home/jobs/{{ .Release.Name }}/complete
-            fi
-          else
-            printf "[ %6d ] Adding user ({{ .Values.userName }})\n" $SECONDS
-            addgroup --gid {{ .Values.groupId }} {{ .Values.groupName }}
-            adduser --disabled-password --uid {{ .Values.userId }} --ingroup {{ .Values.groupName }} --no-create-home --gecos "" {{ .Values.userName }}
-            printf "[ %6d ] User added ($(getent passwd $user > /dev/null))\n" $SECONDS
-            
-            printf "[ %6d ] Waiting for job completion (/home/jobs/{{ .Release.Name }}/complete)\n" $SECONDS
-            while [ ! -f /home/jobs/{{ .Release.Name }}/complete ]; do
-              sleep 10
-            done
-          fi
-          printf "[ %6d ] Exiting, status: $(</home/jobs/{{ .Release.Name }}/complete))\n" $SECONDS
         env:
         - name: POD_IP
           valueFrom:
@@ -130,6 +62,80 @@ kind: ConfigMap
 metadata:
   name: {{ .Release.Name }}-configmap
 data:
+  hpcx-run: |
+    #!/bin/bash
+    
+    SECONDS=0
+      
+    # Correct permissions for the /scratch filesystem
+    chmod 1777 /tmp
+        
+    printf "[ %6d ] Starting SSH daemon\n" $SECONDS
+    /etc/init.d/ssh start
+    
+    printf "[ %6d ] Creating IP file (/home/jobs/{{ .Release.Name }}/hosts/${POD_IP})\n" $SECONDS
+    mkdir -p /home/jobs/{{ .Release.Name }}/hosts
+    touch /home/jobs/{{ .Release.Name }}/hosts/${POD_IP}
+    
+    if [ "${JOB_COMPLETION_INDEX}" = "0" ]; then
+      printf "[ %6d ] Adding user with homedir ({{ .Values.userName }})\n" $SECONDS
+      addgroup --gid {{ .Values.groupId }} {{ .Values.groupName }}
+      adduser --disabled-password --uid {{ .Values.userId }} --ingroup {{ .Values.groupName }} --home /home/{{ .Values.userName }} --gecos "" {{ .Values.userName }}
+      printf "[ %6d ] User added ($(getent passwd {{ .Values.userName }} > /dev/null))\n" $SECONDS
+      
+      if [[ ! -d /home/{{ .Values.userName }}/.ssh ]]; then
+        printf "[ %6d ] Creating ssh key\n" $SECONDS
+        cat <<EOF | sudo -u {{ .Values.userName }} bash
+    ssh-keygen -q -f /home/{{ .Values.userName }}/.ssh/id_rsa -N ''
+    echo -e "Host *\n\tStrictHostKeyChecking no" >> /home/{{ .Values.userName }}/.ssh/config
+    chmod 600 /home/{{ .Values.userName }}/.ssh/config
+    cp /home/{{ .Values.userName }}/.ssh/id_rsa.pub /home/{{ .Values.userName }}/.ssh/authorized_keys
+    echo -e "\n . /opt/openfoam10/etc/bashrc" >> ~/.bashrc
+    EOF
+      else
+        echo -e "SSH keys already exist"
+      fi
+      
+      printf "[ %6d ] Waiting for hosts\n" $SECONDS
+      while [ "$(ls /home/jobs/{{ .Release.Name }}/hosts | wc -l)" != "{{ .Values.numberOfNodes }}" ]; do
+        printf "[ %6d ] - hosts available: $(ls /home/jobs/{{ .Release.Name }}/hosts | wc -l) out of {{ .Values.numberOfNodes }}\n" $SECONDS
+        sleep 10
+      done
+      
+      printf "[ %6d ] Creating hostfile\n" $SECONDS
+      ls /home/jobs/{{ .Release.Name }}/hosts > /home/{{ .Values.userName }}/hostfile
+      printf "[ %6d ] Hostfile contents:\n" $SECONDS
+      cat /home/{{ .Values.userName }}/hostfile
+      chown {{ .Values.userName }}:{{ .Values.groupName }} /home/{{ .Values.userName }}/hostfile
+      chmod +r /home/{{ .Values.userName }}/hostfile
+      
+      printf "[ %6d ] Launching MPI\n" $SECONDS
+      cat <<EOF | su - {{ .Values.userName }}
+      module load mpi/hpcx
+      $@
+
+    EOF
+      RESULT=$?
+      
+      printf "[ %6d ] Writing completion file (/home/jobs/{{ .Release.Name }}/complete)\n" $SECONDS
+      if [ "$RESULT" = "0" ]; then
+        echo "success" > /home/jobs/{{ .Release.Name }}/complete
+      else
+        echo "failure ($RESULT)" > /home/jobs/{{ .Release.Name }}/complete
+      fi
+    else
+      printf "[ %6d ] Adding user ({{ .Values.userName }})\n" $SECONDS
+      addgroup --gid {{ .Values.groupId }} {{ .Values.groupName }}
+      adduser --disabled-password --uid {{ .Values.userId }} --ingroup {{ .Values.groupName }} --no-create-home --gecos "" {{ .Values.userName }}
+      printf "[ %6d ] User added ($(getent passwd $user > /dev/null))\n" $SECONDS
+      
+      printf "[ %6d ] Waiting for job completion (/home/jobs/{{ .Release.Name }}/complete)\n" $SECONDS
+      while [ ! -f /home/jobs/{{ .Release.Name }}/complete ]; do
+        sleep 10
+      done
+    fi
+    printf "[ %6d ] Exiting, status: $(</home/jobs/{{ .Release.Name }}/complete))\n" $SECONDS
+
   openfoam-demo-action: |
     #!/usr/bin/env bash
     
